[package]
name = "pexos"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Daniel Liu <mr.picklepinosaur@gmail.com>"]
description = ""
repository = ""

[features]

[dependencies]
nix = { version = "0.29", features = ["fs", "process", "signal"] }
reqwest = { version = "0.11", features = ["blocking"] }
notify = "6.1"
notify-debouncer-full = "0.3"

lazy_static = "1.5"
regex = "1.10.5"
anyhow = "1.0.86"
