[package]
name = "pexos"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Daniel Liu <mr.picklepinosaur@gmail.com>"]
description = ""
repository = ""

[features]

[dependencies]
nix = { version = "0.29", features = ["fs", "process", "signal"] }
lazy_static = "1.5"
