[build]
target = "armv7-unknown-linux-gnueabihf"

[target.armv7-unknown-linux-gnueabihf]
linker = "/opt/miyoomini-toolchain/usr/bin/arm-linux-gnueabihf-gcc"
rustflags = [
    "-C", "link-arg=--sysroot=/opt/miyoomini-toolchain/arm-buildroot-linux-gnueabihf/sysroot"
]
